/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ReentrancyAttack,
  ReentrancyAttackInterface,
} from "../../../contracts/mocks/ReentrancyAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "escrow_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "attack",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "escrow",
    outputs: [
      {
        internalType: "contract InfraXEscrow",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reentered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102cc3803806102cc83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b610239806100936000396000f3fe6080604052600436106100385760003560e01c80633f09775e146100b35780639e5faafc146100e9578063e2fdcc17146100f157600080fd5b366100ae57600054600160a01b900460ff166100ac57600054604051632e1a7d4d60e01b81523460048201526001600160a01b0390911690632e1a7d4d90602401600060405180830381600087803b15801561009357600080fd5b505af11580156100a7573d6000803e3d6000fd5b505050505b005b600080fd5b3480156100bf57600080fd5b506000546100d490600160a01b900460ff1681565b60405190151581526020015b60405180910390f35b6100ac610129565b3480156100fd57600080fd5b50600054610111906001600160a01b031681565b6040516001600160a01b0390911681526020016100e0565b60008054906101000a90046001600160a01b03166001600160a01b031663d0e30db0346040518263ffffffff1660e01b81526004016000604051808303818588803b15801561017757600080fd5b505af115801561018b573d6000803e3d6000fd5b5050600054604051632e1a7d4d60e01b81523460048201526001600160a01b039091169350632e1a7d4d92506024019050600060405180830381600087803b1580156101d657600080fd5b505af11580156101ea573d6000803e3d6000fd5b50506000805460ff60a01b1916600160a01b179055505056fea2646970667358221220070ff2ae13dfc09f727d351a5706a27d6485dbb75e6e344134718e2aa87687f164736f6c63430008180033";

type ReentrancyAttackConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReentrancyAttackConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReentrancyAttack__factory extends ContractFactory {
  constructor(...args: ReentrancyAttackConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    escrow_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(escrow_, overrides || {});
  }
  override deploy(
    escrow_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(escrow_, overrides || {}) as Promise<
      ReentrancyAttack & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReentrancyAttack__factory {
    return super.connect(runner) as ReentrancyAttack__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAttackInterface {
    return new Interface(_abi) as ReentrancyAttackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReentrancyAttack {
    return new Contract(address, _abi, runner) as unknown as ReentrancyAttack;
  }
}
