/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IInfraXEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOf"
      | "charge"
      | "chargeLimitOf"
      | "chargedToday"
      | "deposit"
      | "depositERC20"
      | "erc20BalanceOf"
      | "pause"
      | "refund"
      | "relayerEnabled"
      | "setChargeDefaultLimit"
      | "setChargeLimit"
      | "setRelayer"
      | "unpause"
      | "withdraw"
      | "withdrawERC20"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChargeDefaultLimitSet"
      | "ChargeLimitSet"
      | "Charged"
      | "Deposited"
      | "Refunded"
      | "RelayerSet"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "charge",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "chargeLimitOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "chargedToday",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "erc20BalanceOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "relayerEnabled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setChargeDefaultLimit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChargeLimit",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "charge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chargeLimitOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chargedToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20BalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "relayerEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChargeDefaultLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChargeLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20",
    data: BytesLike
  ): Result;
}

export namespace ChargeDefaultLimitSetEvent {
  export type InputTuple = [perTx: BigNumberish, perDay: BigNumberish];
  export type OutputTuple = [perTx: bigint, perDay: bigint];
  export interface OutputObject {
    perTx: bigint;
    perDay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChargeLimitSetEvent {
  export type InputTuple = [
    user: AddressLike,
    perTx: BigNumberish,
    perDay: BigNumberish
  ];
  export type OutputTuple = [user: string, perTx: bigint, perDay: bigint];
  export interface OutputObject {
    user: string;
    perTx: bigint;
    perDay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChargedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    ref: string
  ];
  export type OutputTuple = [user: string, amount: bigint, ref: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    ref: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [user: string, amount: bigint, token: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    ref: string
  ];
  export type OutputTuple = [user: string, amount: bigint, ref: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    ref: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerSetEvent {
  export type InputTuple = [relayer: AddressLike, enabled: boolean];
  export type OutputTuple = [relayer: string, enabled: boolean];
  export interface OutputObject {
    relayer: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [user: string, amount: bigint, token: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInfraXEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IInfraXEscrow;
  waitForDeployment(): Promise<this>;

  interface: IInfraXEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOf: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  charge: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, ref: string],
    [bigint],
    "nonpayable"
  >;

  chargeLimitOf: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { perTx: bigint; perDay: bigint }],
    "view"
  >;

  chargedToday: TypedContractMethod<
    [user: AddressLike, day: BigNumberish],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  erc20BalanceOf: TypedContractMethod<
    [token: AddressLike, user: AddressLike],
    [bigint],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  refund: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, ref: string],
    [bigint],
    "nonpayable"
  >;

  relayerEnabled: TypedContractMethod<
    [relayer: AddressLike],
    [boolean],
    "view"
  >;

  setChargeDefaultLimit: TypedContractMethod<
    [perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;

  setChargeLimit: TypedContractMethod<
    [user: AddressLike, perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [relayer: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "charge"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, ref: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "chargeLimitOf"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { perTx: bigint; perDay: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "chargedToday"
  ): TypedContractMethod<
    [user: AddressLike, day: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "erc20BalanceOf"
  ): TypedContractMethod<
    [token: AddressLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, ref: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayerEnabled"
  ): TypedContractMethod<[relayer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setChargeDefaultLimit"
  ): TypedContractMethod<
    [perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setChargeLimit"
  ): TypedContractMethod<
    [user: AddressLike, perTx: BigNumberish, perDay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<
    [relayer: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ChargeDefaultLimitSet"
  ): TypedContractEvent<
    ChargeDefaultLimitSetEvent.InputTuple,
    ChargeDefaultLimitSetEvent.OutputTuple,
    ChargeDefaultLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "ChargeLimitSet"
  ): TypedContractEvent<
    ChargeLimitSetEvent.InputTuple,
    ChargeLimitSetEvent.OutputTuple,
    ChargeLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "Charged"
  ): TypedContractEvent<
    ChargedEvent.InputTuple,
    ChargedEvent.OutputTuple,
    ChargedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerSet"
  ): TypedContractEvent<
    RelayerSetEvent.InputTuple,
    RelayerSetEvent.OutputTuple,
    RelayerSetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "ChargeDefaultLimitSet(uint256,uint256)": TypedContractEvent<
      ChargeDefaultLimitSetEvent.InputTuple,
      ChargeDefaultLimitSetEvent.OutputTuple,
      ChargeDefaultLimitSetEvent.OutputObject
    >;
    ChargeDefaultLimitSet: TypedContractEvent<
      ChargeDefaultLimitSetEvent.InputTuple,
      ChargeDefaultLimitSetEvent.OutputTuple,
      ChargeDefaultLimitSetEvent.OutputObject
    >;

    "ChargeLimitSet(address,uint256,uint256)": TypedContractEvent<
      ChargeLimitSetEvent.InputTuple,
      ChargeLimitSetEvent.OutputTuple,
      ChargeLimitSetEvent.OutputObject
    >;
    ChargeLimitSet: TypedContractEvent<
      ChargeLimitSetEvent.InputTuple,
      ChargeLimitSetEvent.OutputTuple,
      ChargeLimitSetEvent.OutputObject
    >;

    "Charged(address,uint256,string)": TypedContractEvent<
      ChargedEvent.InputTuple,
      ChargedEvent.OutputTuple,
      ChargedEvent.OutputObject
    >;
    Charged: TypedContractEvent<
      ChargedEvent.InputTuple,
      ChargedEvent.OutputTuple,
      ChargedEvent.OutputObject
    >;

    "Deposited(address,uint256,address)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Refunded(address,uint256,string)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "RelayerSet(address,bool)": TypedContractEvent<
      RelayerSetEvent.InputTuple,
      RelayerSetEvent.OutputTuple,
      RelayerSetEvent.OutputObject
    >;
    RelayerSet: TypedContractEvent<
      RelayerSetEvent.InputTuple,
      RelayerSetEvent.OutputTuple,
      RelayerSetEvent.OutputObject
    >;

    "Withdrawn(address,uint256,address)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
